import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  attachWorkerDomain,
  cleanupOrphans,
  createCf,
  deleteD1,
  deleteKv,
  deleteR2Bucket,
  resolveNamePlan,
  wipeNamedResources,
  emailRoutingDashboard,
  enableEmailRouting,
  enableWorkersSubdomain,
  ensureD1,
  ensureKv,
  ensureR2,
  explainCatchAllError,
  getEmailRouting,
  isCfAuthError,
  listDns,
  deleteDnsRecord,
  probePermissions,
  setCatchAllWorker,
  unlockEmailRouting,
} from './cf.mjs';
import { ensurePnpm, pnpmInstall } from './deps.mjs';
import { ensureNode } from './node.mjs';
import { ensureRepo, REPO_URL } from './repo.mjs';

export { REPO_URL };
export const COMPAT_DATE = '2025-06-04';

export function randomJwt() {
  return crypto.randomBytes(32).toString('hex');
}

export function defaultStatePath(root) {
  return path.join(root, '.skymail-state.json');
}

export function loadState(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch {
    return null;
  }
}

export function saveState(file, state) {
  const copy = { ...state };
  delete copy.token;
  fs.writeFileSync(file, JSON.stringify(copy, null, 2), 'utf8');
}

function emit(onEvent, payload) {
  if (typeof onEvent === 'function') onEvent({ ts: new Date().toISOString(), ...payload });
}

function q(value) {
  return JSON.stringify(value);
}

export function renderWranglerToml(opts) {
  const workerName = opts.workerName;
  const accountId = opts.accountId;
  const siteHostname = opts.siteHostname;
  const d1Name = opts.d1Name;
  const d1Id = opts.d1Id;
  const kvId = opts.kvId;
  const r2Name = opts.r2Name;
  const domains = opts.domains;
  const admin = opts.admin;
  const jwtSecret = opts.jwtSecret;
  const enableR2 = opts.enableR2;
  const routes = siteHostname
    ? '[[routes]]\npattern = ' + q(siteHostname) + '\ncustom_domain = true\n'
    : '';
  const r2 = enableR2 && r2Name
    ? '[[r2_buckets]]\nbinding = "r2"\nbucket_name = ' + q(r2Name) + '\n'
    : '';
  return [
    '# generated by skymail-oneclick',
    'name = ' + q(workerName),
    'main = "src/index.js"',
    'compatibility_date = "' + COMPAT_DATE + '"',
    'keep_vars = true',
    'account_id = ' + q(accountId),
    '',
    '[observability]',
    'enabled = true',
    '',
    routes,
    '[[d1_databases]]',
    'binding = "db"',
    'database_name = ' + q(d1Name),
    'database_id = ' + q(d1Id),
    '',
    '[[kv_namespaces]]',
    'binding = "kv"',
    'id = ' + q(kvId),
    '',
    r2,
    '[ai]',
    'binding = "ai"',
    '',
    '[assets]',
    'binding = "assets"',
    'directory = "./dist"',
    'not_found_handling = "single-page-application"',
    'run_worker_first = true',
    '',
    '[triggers]',
    'crons = ["0 * * * *"]',
    '',
    '[vars]',
    'domain = ' + q(domains),
    'admin = ' + q(admin),
    'jwt_secret = ' + q(jwtSecret),
    '',
  ].join('\n');
}

async function waitForInit(urls, jwt, onEvent) {
  const pathSuffix = '/api/init/' + encodeURIComponent(jwt);
  let lastErr = null;
  for (let i = 0; i < 18; i++) {
    for (let u = 0; u < urls.length; u++) {
      const base = urls[u];
      const url = base.replace(/\/$/, '') + pathSuffix;
      emit(onEvent, { step: 'init', status: 'run', message: 'init attempt ' + (i + 1) + ' -> ' + base });
      try {
        const res = await fetch(url, { method: 'GET' });
        const text = (await res.text()).trim();
        emit(onEvent, { step: 'init', status: 'log', message: 'HTTP ' + res.status + ' ' + text.slice(0, 200) });
        if (res.ok && /success/i.test(text)) return { ok: true, url: base, text };
      } catch (e) {
        lastErr = e;
        emit(onEvent, { step: 'init', status: 'log', message: e.message });
      }
    }
    await new Promise((r) => setTimeout(r, 5000));
  }
  return { ok: false, error: lastErr ? lastErr.message : 'init timeout' };
}

function isCfMx(content) {
  return /mx\.cloudflare\.net/i.test(content || '');
}

async function prepareEmailRouting(cf, zone, opts) {
  const replaceMx = opts.replaceMx;
  const workerName = opts.workerName;
  const onEvent = opts.onEvent;
  const accountId = opts.accountId;
  const dashboard = emailRoutingDashboard(accountId, zone.id);
  const out = {
    zone: { id: zone.id, name: zone.name },
    dashboard,
    settings: null,
    catchAll: null,
    ok: false,
    warning: null,
  };
  emit(onEvent, { step: 'email', status: 'run', message: 'Email Routing for ' + zone.name });
  let settings = null;
  try {
    settings = await getEmailRouting(cf, zone.id);
    out.settings = settings;
  } catch (e) {
    emit(onEvent, { step: 'email', status: 'log', message: 'read routing: ' + e.message });
  }

  const mx = await listDns(cf, zone.id, 'MX');
  const foreignMx = mx.filter((r) => !isCfMx(r.content));
  if (foreignMx.length && !replaceMx) {
    throw new Error(
      zone.name +
        ' already has non-Cloudflare MX: ' +
        foreignMx.map((r) => r.content).join(', ') +
        '. Enable replaceMx to take over inbound mail.'
    );
  }
  if (foreignMx.length && replaceMx) {
    for (let i = 0; i < foreignMx.length; i++) {
      const rec = foreignMx[i];
      emit(onEvent, { step: 'email', status: 'log', message: 'delete MX ' + rec.name + ' -> ' + rec.content });
      await deleteDnsRecord(cf, zone.id, rec.id);
    }
  }

  const enabled = settings && (settings.enabled === true || settings.status === 'enabled');
  if (!enabled) {
    emit(onEvent, { step: 'email', status: 'log', message: 'enable Email Routing DNS on ' + zone.name });
    await enableEmailRouting(cf, zone.id);
    await new Promise((r) => setTimeout(r, 1500));
  }
  if (settings && settings.skip_wizard === false) {
    emit(onEvent, { step: 'email', status: 'log', message: 'unlock Email Routing wizard on ' + zone.name });
    try {
      await unlockEmailRouting(cf, zone.id);
    } catch (e) {
      emit(onEvent, { step: 'email', status: 'log', message: 'unlock routing: ' + e.message });
    }
  }

  emit(onEvent, { step: 'email', status: 'log', message: 'catch-all -> worker ' + workerName });
  let catchAll = null;
  let lastErr = null;
  for (let i = 0; i < 2; i++) {
    try {
      catchAll = await setCatchAllWorker(cf, zone.id, workerName);
      lastErr = null;
      break;
    } catch (e) {
      lastErr = e;
      emit(onEvent, { step: 'email', status: 'log', message: 'catch-all retry ' + (i + 1) + ': ' + e.message });
      if (isCfAuthError(e) && i === 0) {
        await new Promise((r) => setTimeout(r, 1500));
        continue;
      }
      if (isCfAuthError(e)) break;
      await new Promise((r) => setTimeout(r, 2000));
    }
  }
  if (lastErr) {
    const warning = explainCatchAllError(lastErr);
    out.warning = warning;
    out.ok = false;
    emit(onEvent, { step: 'email', status: 'warn', message: warning + ' 控制台: ' + dashboard });
    return out;
  }
  out.catchAll = catchAll;
  out.ok = true;
  return out;
}

export async function deploy(input, onEvent) {
  const started = Date.now();
  const token = input.token ? String(input.token).trim() : '';
  const accountId = input.accountId ? String(input.accountId).trim() : '';
  let workerName = (input.workerName || 'cloud-mail').trim();
  const siteHostname = (input.siteHostname || '').trim().toLowerCase();
  const mailDomains = input.mailDomains || [];
  const admin = (input.admin || '').trim().toLowerCase();
  const enableR2 = input.enableR2 !== false;
  const replaceMx = Boolean(input.replaceMx);
  const root = input.root;
  const workDir = input.workDir || path.join(root, 'work');
  let jwtSecret = (input.jwtSecret || '').trim();
  const nameStrategy = input.nameStrategy === 'suffix' || input.nameStrategy === 'replace' ? input.nameStrategy : 'reuse';

  if (!token) throw new Error('Missing API Token');
  if (!accountId) throw new Error('Missing Account ID');
  if (!mailDomains.length) throw new Error('Select at least one mail domain');
  if (!admin || admin.indexOf('@') < 0) throw new Error('Invalid admin email');

  const domains = mailDomains.map((z) => z.name);
  const cf = createCf(token);
  const result = {
    workerName,
    accountId,
    siteHostname,
    domains,
    admin,
    jwtSecret,
    urls: {},
    resources: {},
  };
  const createdThisRun = { d1: false, kv: false, r2: false };
  let workerPublished = false;
  result.warnings = [];
  result.emailRouting = [];
  const partialFile = path.join(root, '.skymail-partial.json');
  const writePartial = () => {
    fs.writeFileSync(partialFile, JSON.stringify({
      accountId,
      workerName,
      createdThisRun,
      resources: result.resources,
      ts: new Date().toISOString(),
    }, null, 2), 'utf8');
  };
  const clearPartial = () => { try { fs.unlinkSync(partialFile); } catch {} };

  try {
  emit(onEvent, { step: 'plan', status: 'run', message: 'Resolve names (' + nameStrategy + ') for ' + workerName });
  const plan = await resolveNamePlan(cf, accountId, workerName, nameStrategy);
  result.plan = { strategy: plan.strategy, action: plan.action, wanted: plan.wanted, finalName: plan.finalName, hits: plan.hits };
  if (plan.action === 'replace') {
    emit(onEvent, { step: 'plan', status: 'run', message: 'Deleting existing ' + (plan.hits.join(', ') || workerName) });
    const wiped = await wipeNamedResources(cf, accountId, workerName);
    emit(onEvent, { step: 'plan', status: 'ok', message: wiped.deleted.length ? 'deleted ' + wiped.deleted.join('; ') : 'nothing to delete' });
  } else if (plan.action === 'suffix') {
    emit(onEvent, { step: 'plan', status: 'ok', message: 'Name in use: ' + plan.hits.join(', ') + ' -> use ' + plan.finalName });
  } else if (plan.action === 'reuse') {
    emit(onEvent, { step: 'plan', status: 'ok', message: 'Reuse ' + plan.hits.join(', ') });
  } else {
    emit(onEvent, { step: 'plan', status: 'ok', message: 'Create new ' + plan.finalName });
  }
  workerName = plan.finalName;
  result.workerName = workerName;
  if (!jwtSecret && plan.action === 'reuse') {
    const prev = loadState(defaultStatePath(root));
    if (prev && prev.jwtSecret && prev.accountId === accountId && prev.workerName === workerName) {
      jwtSecret = prev.jwtSecret;
      emit(onEvent, { step: 'plan', status: 'log', message: 'Reused jwt_secret from last successful deploy' });
    }
  }
  if (!jwtSecret) jwtSecret = randomJwt();
  result.jwtSecret = jwtSecret;

  emit(onEvent, { step: 'probe', status: 'run', message: 'Checking token permissions' });
  const probeZoneId = mailDomains[0] && mailDomains[0].id;
  const checks = await probePermissions(cf, accountId, probeZoneId);
  result.permissions = checks;
  const must = ['d1', 'kv', 'workers'];
  const missing = checks.filter((c) => must.indexOf(c.id) >= 0 && !c.ok);
  if (missing.length) {
    throw new Error('Token missing permissions: ' + missing.map((m) => m.label + ' (' + m.error + ')').join('; '));
  }
  const emailRouting = checks.find((c) => c.id === 'email_routing');
  const emailRules = checks.find((c) => c.id === 'email_rules');
  if (
    emailRouting &&
    emailRouting.ok &&
    emailRules &&
    !emailRules.ok &&
    isCfAuthError({ message: emailRules.error, status: emailRules.status })
  ) {
    throw new Error(explainCatchAllError({ message: emailRules.error, status: emailRules.status }));
  }
  if (emailRules && !emailRules.ok) {
    emit(onEvent, { step: 'probe', status: 'warn', message: 'Email Routing Rules probe: ' + emailRules.error });
  }
  const r2Check = checks.find((c) => c.id === 'r2');
  const useR2 = enableR2 && (!r2Check || r2Check.ok);
  if (enableR2 && r2Check && !r2Check.ok) {
    emit(onEvent, { step: 'probe', status: 'warn', message: 'R2 unavailable, skip attachments: ' + r2Check.error });
  }
  emit(onEvent, { step: 'probe', status: 'ok', message: 'Permission check done', data: checks });

  emit(onEvent, { step: 'd1', status: 'run', message: 'Ensure D1 ' + workerName });
  const d1 = await ensureD1(cf, accountId, workerName);
  result.resources.d1 = d1;
  createdThisRun.d1 = Boolean(d1.created);
  writePartial();
  emit(onEvent, { step: 'd1', status: 'ok', message: (d1.created ? 'created' : 'reused') + ' D1 ' + d1.id });

  emit(onEvent, { step: 'kv', status: 'run', message: 'Ensure KV ' + workerName + '-kv' });
  const kv = await ensureKv(cf, accountId, workerName + '-kv');
  result.resources.kv = kv;
  createdThisRun.kv = Boolean(kv.created);
  writePartial();
  emit(onEvent, { step: 'kv', status: 'ok', message: (kv.created ? 'created' : 'reused') + ' KV ' + kv.id });

  let r2 = null;
  if (useR2) {
    const bucket = workerName.toLowerCase().replace(/[^a-z0-9-]/g, '-') + '-r2';
    emit(onEvent, { step: 'r2', status: 'run', message: 'Ensure R2 ' + bucket });
    try {
      r2 = await ensureR2(cf, accountId, bucket);
      result.resources.r2 = r2;
      createdThisRun.r2 = Boolean(r2.created);
      writePartial();
      emit(onEvent, { step: 'r2', status: 'ok', message: (r2.created ? 'created' : 'reused') + ' R2 ' + bucket });
    } catch (e) {
      emit(onEvent, { step: 'r2', status: 'warn', message: 'R2 failed, continue without attachments: ' + e.message });
    }
  } else {
    emit(onEvent, { step: 'r2', status: 'skip', message: 'Skip R2' });
  }

  emit(onEvent, { step: 'subdomain', status: 'run', message: 'Enable workers.dev if needed' });
  result.workersSubdomain = await enableWorkersSubdomain(cf, accountId);
  emit(onEvent, { step: 'subdomain', status: 'ok', message: 'workers.dev ready' });

  const repoDir = await ensureRepo(workDir, onEvent);
  emit(onEvent, { step: 'clone', status: 'ok', message: repoDir });

  const mailWorkerDir = path.join(repoDir, 'mail-worker');
  const toml = renderWranglerToml({
    workerName,
    accountId,
    siteHostname,
    d1Name: workerName,
    d1Id: d1.id,
    kvId: kv.id,
    r2Name: r2 ? r2.name : null,
    domains,
    admin,
    jwtSecret,
    enableR2: Boolean(r2),
  });
  fs.writeFileSync(path.join(mailWorkerDir, 'wrangler.toml'), toml, 'utf8');
  emit(onEvent, { step: 'toml', status: 'ok', message: 'Wrote wrangler.toml' });

  const mailVueDir = path.join(repoDir, 'mail-vue');
  const node = await ensureNode(root, onEvent);
  const pnpm = await ensurePnpm(root, onEvent, node);
  await pnpmInstall(pnpm, mailWorkerDir, onEvent, 'install');
  await pnpmInstall(pnpm, mailVueDir, onEvent, 'vue');

  emit(onEvent, { step: 'vue', status: 'run', message: 'Build mail-vue (vite -> mail-worker/dist)' });
  await pnpm.run(['run', 'build'], {
    cwd: mailVueDir,
    timeout: 600000,
    onLog: (x) => emit(onEvent, { step: 'vue', status: 'log', message: x.text }),
  });
  const distDir = path.join(mailWorkerDir, 'dist');
  if (!fs.existsSync(distDir)) throw new Error('mail-vue build did not produce mail-worker/dist');
  emit(onEvent, { step: 'vue', status: 'ok', message: 'Frontend built at ' + distDir });

  emit(onEvent, { step: 'deploy', status: 'run', message: 'wrangler deploy' });
  const deployOut = await pnpm.run(['wrangler', 'deploy'], {
    cwd: mailWorkerDir,
    timeout: 600000,
    env: {
      CLOUDFLARE_API_TOKEN: token,
      CLOUDFLARE_ACCOUNT_ID: accountId,
      WRANGLER_SEND_METRICS: 'false',
    },
    onLog: (x) => emit(onEvent, { step: 'deploy', status: 'log', message: x.text }),
  });
  emit(onEvent, { step: 'deploy', status: 'ok', message: 'Worker published' });
  workerPublished = true;

  const workersDev = extractWorkersDev(deployOut.stdout + '\n' + deployOut.stderr, workerName);
  if (workersDev) result.urls.workersDev = workersDev;

  if (siteHostname) {
    const zoneForSite = pickZoneForHostname(mailDomains, input.allZones || mailDomains, siteHostname);
    if (zoneForSite) {
      emit(onEvent, { step: 'domain', status: 'run', message: 'Attach custom domain ' + siteHostname });
      try {
        const attached = await attachWorkerDomain(cf, accountId, {
          hostname: siteHostname,
          service: workerName,
          zoneId: zoneForSite.id,
        });
        result.resources.customDomain = attached;
        emit(onEvent, {
          step: 'domain',
          status: 'ok',
          message: (attached.created ? 'attached' : 'exists') + ' ' + siteHostname,
        });
      } catch (e) {
        emit(onEvent, {
          step: 'domain',
          status: 'warn',
          message: 'Custom domain API failed (wrangler routes may already apply): ' + e.message,
        });
      }
    }
    result.urls.site = 'https://' + siteHostname;
  }

  for (let i = 0; i < mailDomains.length; i++) {
    const zone = mailDomains[i];
    const er = await prepareEmailRouting(cf, zone, { replaceMx, workerName, onEvent, accountId });
    result.emailRouting.push({
      zone: er.zone,
      ok: er.ok,
      warning: er.warning,
      dashboard: er.dashboard,
      skipped: Boolean(er.catchAll && er.catchAll.skipped),
    });
    if (er.ok) {
      emit(onEvent, { step: 'email', status: 'ok', message: zone.name + ' catch-all -> ' + workerName });
    } else {
      result.warnings.push({
        step: 'email',
        zone: zone.name,
        message: er.warning,
        dashboard: er.dashboard,
      });
    }
  }

  const initUrls = [];
  if (result.urls.site) initUrls.push(result.urls.site);
  if (result.urls.workersDev) initUrls.push(result.urls.workersDev);
  const init = await waitForInit(initUrls, jwtSecret, onEvent);
  result.init = init;
  emit(onEvent, {
    step: 'init',
    status: init.ok ? 'ok' : 'warn',
    message: init.ok ? 'Database initialized' : 'Auto init incomplete: ' + init.error,
  });

  result.elapsedMs = Date.now() - started;
  result.host = os.hostname();
  clearPartial();
  emit(onEvent, { step: 'done', status: 'ok', message: 'Deploy finished', data: sanitizeResult(result) });
  return result;
  } catch (err) {
    if (workerPublished) {
      emit(onEvent, {
        step: 'rollback',
        status: 'warn',
        message: 'Worker 已发布，保留本次 D1/KV/R2，避免 Worker 绑到已删除存储。失败步骤请看日志；Catch-all 可在 Cloudflare Email Routing 控制台补设。',
      });
      clearPartial();
      throw err;
    }
    emit(onEvent, { step: 'rollback', status: 'run', message: 'Deploy failed, rolling back resources created in this run only' });
    try {
      const deleted = [];
      if (createdThisRun.d1 && result.resources.d1 && result.resources.d1.id) {
        await deleteD1(cf, accountId, result.resources.d1.id);
        deleted.push('d1:' + result.resources.d1.id);
      }
      if (createdThisRun.kv && result.resources.kv && result.resources.kv.id) {
        await deleteKv(cf, accountId, result.resources.kv.id);
        deleted.push('kv:' + result.resources.kv.id);
      }
      if (createdThisRun.r2 && result.resources.r2 && result.resources.r2.name) {
        await deleteR2Bucket(cf, accountId, result.resources.r2.name);
        deleted.push('r2:' + result.resources.r2.name);
      }
      emit(onEvent, { step: 'rollback', status: 'ok', message: deleted.length ? 'deleted ' + deleted.join('; ') : 'reused resources kept' });
    } catch (re) {
      emit(onEvent, { step: 'rollback', status: 'warn', message: 'rollback failed: ' + re.message });
    }
    clearPartial();
    throw err;
  }
}

function extractWorkersDev(text, workerName) {
  const re = new RegExp('https://' + workerName + '[a-z0-9.-]*\\.workers\\.dev', 'i');
  const m = text.match(re) || text.match(/https:\/\/[a-z0-9.-]+\.workers\.dev/i);
  return m ? m[0] : null;
}

function pickZoneForHostname(mailDomains, allZones, hostname) {
  const exact = allZones.find((z) => z.name === hostname);
  if (exact) return exact;
  const suffix = allZones
    .filter((z) => hostname === z.name || hostname.endsWith('.' + z.name))
    .sort((a, b) => b.name.length - a.name.length)[0];
  return suffix || mailDomains[0] || null;
}

export function sanitizeResult(result) {
  const copy = JSON.parse(JSON.stringify(result));
  if (copy.jwtSecret) copy.jwtSecretMasked = copy.jwtSecret.slice(0, 6) + '...';
  return copy;
}